### PR TITLE
Prepare the first release

### PR DESCRIPTION
**Pull request by fgksgf**

### CODE REVIEW

**Comment by fgksgf** [comment]
@kezhenxu94 @wu-sheng Do we need update the [changes.md](https://github.com/apache/skywalking-kubernetes-event-exporter/blob/main/CHANGES.md#change-log) ?

**Comment by wu-sheng** [comment]
The first release, the changelog doesn't matter much. You could write one about what this project plans to do, don't need to include the detail

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Don't forget to apply dockerhub repo for this release, I think you need it.

**Comment by fgksgf** [comment]
> The first release, the changelog doesn't matter much. You could write one about what this project plans to do, don't need to include the detail

Ok, but i have no idea about what this project plans to do, since the main feature (exporting k8s events) we already have.

> Don't forget to apply dockerhub repo for this release, I think you need it.

Yes, I applied it yesterday and the repo has been created now.

**Pull request merged**
